#!/bin/sh
# Creates the wallet_app role, if it does not exist yet, and sets its
# password. The role and its credential are cluster objects, so they belong
# here, in provisioning - never in a migration. This is the ONLY place in
# the whole repository that ever creates that role or sets a real password
# for it - never a migration, never the Compose file - so no credential is
# versioned in SQL, and migrations/0002_app_role.up.sql only grants
# schema-level privileges to a role this script has already guaranteed
# exists.
#
# Idempotent by design, the same way deploy/ministack/provision.sh is: a
# random password is generated only the first time and then reused on
# every later run, reading it back from the credentials file this script
# itself wrote. That is what lets `docker compose stop && docker compose
# up --build` (no volume wipe) reapply the exact same ALTER ROLE instead of
# rotating a credential the test suite, or a running app, might still be
# holding.
set -eu

OWNER_DSN="${OWNER_DATABASE_URL:?OWNER_DATABASE_URL is required}"
RUNTIME_DIR="${POSTGRES_RUNTIME_DIR:-/shared}"
CREDENTIALS_FILE="${POSTGRES_CREDENTIALS_FILE:-$RUNTIME_DIR/credentials.env}"

umask 077
mkdir -p "$RUNTIME_DIR"
chmod 0700 "$RUNTIME_DIR"

# Load whatever password a previous run already wrote, so a second
# `docker compose up` reuses it instead of minting a new one.
WALLET_APP_PASSWORD=""
if [ -f "$CREDENTIALS_FILE" ]; then
	# shellcheck disable=SC1090
	. "$CREDENTIALS_FILE"
fi

if [ -z "$WALLET_APP_PASSWORD" ]; then
	# 32 random bytes, URL-safe base64 with padding stripped: no quote,
	# slash or plus character can ever appear, so the value is safe to
	# splice into the ALTER ROLE statement below without escaping.
	WALLET_APP_PASSWORD=$(head -c 32 /dev/urandom | base64 | tr '+/' '-_' | tr -d '=\n')
	echo "postgres-provisioning: generated a new wallet_app password"
else
	echo "postgres-provisioning: reusing existing wallet_app password"
fi

echo "postgres-provisioning: ensuring the wallet_app role exists"
psql "$OWNER_DSN" -v ON_ERROR_STOP=1 -c "
DO \$\$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'wallet_app') THEN
        CREATE ROLE wallet_app LOGIN PASSWORD NULL;
    END IF;
END
\$\$;
" >/dev/null

# wallet_app's own DSN, built by swapping OWNER_DSN's userinfo - used
# below to prove the password actually works, not just that some password
# is set.
APP_DSN="postgres://wallet_app:${WALLET_APP_PASSWORD}@${OWNER_DSN#*@}"

# Verified with a real password-authenticated connection as wallet_app, not
# just an exit code or a NOT NULL check on pg_authid (either of which would
# stay "green" even if the ALTER ROLE below landed against a stale or
# about-to-be-superseded backend right after Postgres's own first-boot
# initdb sequence): retrying the ALTER ROLE itself, not just the check, is
# what makes this self-healing instead of racy against that narrow window.
i=0
while :; do
	psql "$OWNER_DSN" -v ON_ERROR_STOP=1 -c "ALTER ROLE wallet_app WITH PASSWORD '${WALLET_APP_PASSWORD}'" >/dev/null
	if psql "$APP_DSN" -tAc "SELECT 1" 2>/dev/null | grep -q '^1$'; then
		break
	fi
	i=$((i + 1))
	if [ "$i" -ge 10 ]; then
		echo "postgres-provisioning: wallet_app password did not authenticate after retries" >&2
		exit 1
	fi
	echo "postgres-provisioning: password not yet usable, retrying ALTER ROLE"
	sleep 1
done

cat >"$CREDENTIALS_FILE" <<EOF
# Generated by deploy/postgres/provision.sh on every \`docker compose up\`.
# wallet_app's own password - never versioned, reused across runs so a
# second \`docker compose up --build\` does not rotate it. Read by
# test/integration (see helpers_test.go) and by the app container itself
# (internal/pg.AppDSN, via DATABASE_APP_CREDENTIALS_FILE) - the only two
# things ever allowed to see it.
WALLET_APP_PASSWORD=${WALLET_APP_PASSWORD}
EOF
chmod 0600 "$CREDENTIALS_FILE"

# The app container runs as a fixed non-root UID/GID (see Dockerfile,
# docker-compose.yml's APP_RUNTIME_UID/APP_RUNTIME_GID) and mounts this
# exact file read-only; without this chown it would stay owned by
# whichever user ran this script (root, in the postgres:16-alpine image)
# and a 0600 mode would make it unreadable to the app - the same problem
# deploy/ministack/provision.sh already solves for app-credentials.env.
# A failure here must not pass silently: the app would otherwise fail much
# later, and far less clearly, when it cannot open the credentials file at
# all.
APP_RUNTIME_UID="${APP_RUNTIME_UID:-10001}"
APP_RUNTIME_GID="${APP_RUNTIME_GID:-10001}"
if ! chown "${APP_RUNTIME_UID}:${APP_RUNTIME_GID}" "$CREDENTIALS_FILE"; then
	echo "postgres-provisioning: failed to chown $CREDENTIALS_FILE to ${APP_RUNTIME_UID}:${APP_RUNTIME_GID} - the app container will not be able to read its Postgres credentials" >&2
	exit 1
fi

echo "postgres-provisioning: done, credentials written to $CREDENTIALS_FILE"
